### ISSUE TITLE
Move block number to its own column

### ISSUE THREAD

**Issue by michaelbnewman** [Determinant/avax-staking-history#1]
CSV data would be easier to use/import if the block number is simply a new column within the existing records.

Change:
`Tx ID,Address,Reward Type,nAVAX,Node,Time`
to:
`Tx ID,Address,Reward Type,nAVAX,Node,Time,Block`

**Comment by Determinant** [comment]
Fixed this in https://github.com/Determinant/avax-staking-history/commit/2db5c6390100dd7514d45d8739df9fff73966d80
